ALL_ATTRIBUTES:
  - wearing_lipstick
  - mouth_slightly_open
  - smiling
  - bushy_eyebrows
  - arched_eyebrows
  - narrow_eyes
  - pointy_nose
  - big_nose
  - black_hair
  - brown_hair
  - blond_hair
  - gray_hair
  - wavy_hair
  - straight_hair

OPTIMIZER:
  LR_LATENT: 0.001
  LR_NOISE: 0.1
  REINIT: True

GPU: True

N_ITER_PRINT: 100
N_LATENT_STEPS: 1000
N_NOISE_STEPS: 500

MODELS:
  SEGMENTATOR:
    N_CLASSES: 9
    CHANGE_EYEBROWS: False
    CKPT: 'FaceParser.ckpt'
    UPDATE_SHAPE: False
  CLASSIFIER:
    CKPT: 'BranchedTiny.ckpt'

LOSS:
  weights:
    classf: 0.005
    mse: 2
    seg: 0.5
    n_loss: 1
    size: 1
  start_steps:
    classf: 500
    mse: 0
    seg: 500
    n_loss: 0

DYNAMIC_MASKING: True
DYNAMIC_MASKING_ITERS: 200

# Attribute prediction
SMOOTHING: 0.05

# Size manipulation
SIZE: 0.

TRACK_PROGRESS: False
OUTDIR: 'output'
